export const COMPANY_FORM_REQUEST = "COMPANY_FORM_REQUEST";
export const COMPANY_FORM_SUCCESS = "COMPANY_FORM_SUCCESS";
export const COMPANY_FORM_FAIL = "COMPANY_FORM_FAIL";

export const INDIVIDUAL_FORM_REQUEST = "INDIVIDUAL_FORM_REQUEST";
export const INDIVIDUAL_FORM_SUCCESS = "INDIVIDUAL_FORM_SUCCESS";
export const INDIVIDUAL_FORM_FAIL = "INDIVIDUAL_FORM_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const FORM_SUBMIT_REQUEST = "FORM_SUBMIT_REQUEST";
export const FORM_SUBMIT_SUCCESS = "FORM_SUBMIT_SUCCESS";
export const FORM_SUBMIT_FAIL = "FORM_SUBMIT_FAIL";

export const RESET_FORM_SUCCESS = "RESET_FORM_SUCCESS";
